etcd:
    image: microbox/etcd
    ports:
        - "4001:4001"
        - "7001:7001"

loadbalancer:
    image: eher/nginx-lb
    ports:
        - "80:80"
    environment:
        - ETCD_IP: etcd
    links:
        - etcd
        - helena
        - leitoranaholanda
        - paginasbrancas
        - queroservoluntario

mysql:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=1234
    ports:
        - "3306:3306"

galeracluster:
    image: paulczar/percona-galera

helena:
    image: wordpress
    environment:
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_NAME=helena
        - WORDPRESS_DB_PASSWORD=1234
    links:
        - mysql

leitoranaholanda:
    image: wordpress
    environment:
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_NAME=leitoranaholanda
        - WORDPRESS_DB_PASSWORD=1234
    links:
        - mysql:mysql

paginasbrancas:
    image: eher/nginx

queroservoluntario:
    image: eher/nginx
    links:
        - mysql

teamcityserver:
    image: eher/teamcity-server
    ports:
        - "8111:8111"
    environment:
        - TEAMCITY_PACKAGE TeamCity-9.0.3.tar.gz
        - TEAMCITY_DOWNLOAD http://download.jetbrains.com/teamcity

teamcityagent:
    image: eher/teamcity-agent
    links:
        - teamcityserver
    environment:
        - TEAMCITY_SERVER=http://teamcityserver:8111
